### ISSUE TITLE
about anet feature

### ISSUE THREAD

**Issue by menghuaa** [xlliu7/TadTR#13]
Hello, can you provide the TSN features after linear interpolation of activitynet1.3？

**Comment by xlliu7** [comment]
Hi @menghuaa . You can download the TSN features shared by Tianwei Lin [here](https://github.com/wzmsltw/BSN-boundary-sensitive-network.pytorch). But note that TSN features are somewhat weak. I strongly recommend you to use the TSP feature, which can be downloaded [here](https://github.com/HumamAlwassel/TSP).

**Comment by menghuaa** [comment]
> 你好@menghuaa. [您可以在此处](https://github.com/wzmsltw/BSN-boundary-sensitive-network.pytorch)下载林天威分享的 TSN 功能。但请注意，TSN 功能有些薄弱。我强烈建议您使用 TSP 功能，可在[此处](https://github.com/HumamAlwassel/TSP)下载。
Hello, RTD-Net also uses transformer to realize the generation of Temporal Action Proposal, but it mentioned that due to the slowness problem of video features, it will use the TEM module of BSN to generate the start and end probability of each location, and then multiply it with the corresponding video features to weaken the slowness problem. You use transformer to realize sequential action detection. Have you encountered the slowness problem of video feature? If you encounter it, how do you solve it?

**Comment by xlliu7** [comment]
No. We do not need this trick.
