### ISSUE TITLE
code releasing date

### ISSUE THREAD

**Issue by alexzeng1206** [xlliu7/TadTR#14]
Thanks for your great work. When will the training & inference code release? Can you give an approximate date? Thanks!

**Comment by xlliu7** [comment]
Hi. I plan to release the code of TadTR in the second half of June.

**Comment by alexzeng1206** [comment]
Thanks!

**Comment by sauradip** [comment]
HI ! This is already second half of june ! Is it possible to upload the training/inference code ? Atleast making the dataloader public can also help

**Comment by xlliu7** [comment]
I am working on it. Hopefully, it will be uploaded within one day.
