### ISSUE TITLE
 E2E-TAD code

### ISSUE THREAD

**Issue by bnu-wangxun** [xlliu7/TadTR#15]
Do you have a planed time to release the code of E2E-TAD?

**Comment by xlliu7** [comment]
Hi, I have released the code of TadTR. E2E-TAD is based on TadTR and relies on a few extra modules. I plan to release the code in this weekend.

**Comment by xlliu7** [comment]
Hi @bnu-wangxun 
I have released the inference code of E2E-TAD. I am still checking the training code. Will add it soon.
