### ISSUE TITLE
How to generate th14_i3d2s_ft_info.json?

### ISSUE THREAD

**Issue by Gttgithub** [xlliu7/TadTR#17]
Hello, thank you for your good work!
I want to know how to generate th14_i3d2s_ft_info.json for thumos14 video features. And how to compute ''feature_length", "feature_second" and "feature_fps" for each video?

**Comment by yyccli** [comment]
The information in this json file mainly depends on how you extract video features from raw videos.
`feature_length` can be read directly from the video feature files.
In TadTR paper, it says 1 video feature is extracted from 8 frames with no overlap from the raw video, which means if the raw video is 30fps, then its `feature fps` is 30/8=3.75.
When you get `feature_length` and `feature_fps`, the `feature_second` is computed by `feature_length` / `feature_fps`.

**Comment by xlliu7** [comment]
@yyccli's explanation is correct.
