### ISSUE TITLE
Request code for ActivityNet

### ISSUE THREAD

**Issue by takfate** [xlliu7/TadTR#18]
Hello, thanks for the nice work.
I have sent an email to request you the codes for ActivityNet.
Could you share your codes?

Best wishes.

**Comment by xlliu7** [comment]
Hi, I have received many emails recently. I don't know which one is yours. Can you leave your email address?

**Comment by takfate** [comment]
I sent the email to liuxl@hust.edu.cn. 
Is this your present email address?

**Comment by xlliu7** [comment]
yes

**Comment by 0829MingHu** [comment]
Hey,bro, I just sent you an email. I am reproducing your model on my own dataset. Could you share your code on activitynet with me?Thanks a lot.

**Comment by xlliu7** [comment]
@takfate @0829MingHu 
I have sent the code via email to you.

**Comment by andypinxinliu** [comment]
Hi, would you share the code for activitynet and also the features of activitynet as well? I have sent an email to you as well. I would really appreciate your help if you would be willing to provide that for activitynet 1.3.

**Comment by Mayhyy** [comment]
> Hey,bro, I just sent you an email. I am reproducing your model on my own dataset. Could you share your code on activitynet with me?Thanks a lot.嘿，兄弟，我刚给你发了电子邮件。 我放你的模型在我自己的数据集。 你可以分享你的代码 activitynet 我吗？非常感谢。

Have you reproduced the results on the ActivityNet1.3 dataset? Would you share the code for activitynet and also the features of activitynet? My email address is cfh20011018@163.com, thank you very much!

**Comment by Mayhyy** [comment]
> I sent the email to [liuxl@hust.edu.cn](mailto:liuxl@hust.edu.cn).我发送邮件 [liuxl@hust.edu.cn](mailto:liuxl@hust.edu.cn). Is this your present email address?这是你的本子邮件地址？

Have you reproduced the results on the ActivityNet1.3 dataset? Would you share the code for activitynet and also the features of activitynet? My email address is [cfh20011018@163.com](mailto:cfh20011018@163.com), thank you very much!
