### ISSUE TITLE
When will the code be available?

### ISSUE THREAD

**Issue by tobyperrett** [xlliu7/TadTR#2]
Hi. The arxiv paper says code will be made available here. Do you have a date when you plan to release it? Thanks.

**Comment by xlliu7** [comment]
Hi @tobyperrett 
The code will be release in two weeks.

**Comment by colaaaaaa** [comment]
> Hi @tobyperrett
> The code will be release in two weeks.

when...

**Comment by tobyperrett** [comment]
Hi. Any update on this? Thanks.

**Comment by xlliu7** [comment]
Thanks for your interest in our work. Sorry for the delay. I've been busy with another research project. I have uploaded the model code and will upload the inference code soon. We're still improving this work and will upload the full code after it is finished.
