### ISSUE TITLE
ImportError: cannot import name 'TemporalDeformableAttention' from 'models.ops.temporal_deform_attn'

### ISSUE THREAD

**Issue by liyunfan13** [xlliu7/TadTR#5]
I encountered the above error when trying to run the demo code.

**Comment by xlliu7** [comment]
Did you successfully compile the CUDA extensions? “TemporalDeformableAttention” is a CUDA extension that must be compiled first.

**Comment by liyunfan13** [comment]
The problem was fixed after compiling. Thanks!
