### ISSUE TITLE
One question about the loss backward of temporal_deform_attn

### ISSUE THREAD

**Issue by kimsimple** [xlliu7/TadTR#9]
Thanks open source for this good work.

But, I met a problem.

`models/ops/temporal_deform_attn/functions/temporal_deform_attn_func.py", line 40, in backward
    value, value_spatial_shapes, value_level_start_index, sampling_locations, attention_weights, grad_output, ctx.seq2col_step)
RuntimeError: Not implemented`

I wonder if it is convenient for you to answer.

**Comment by fightingaaa** [comment]
I met the same problem

**Comment by kimsimple** [comment]
> I met the same problem

QQ：2829334266

**Comment by fightingaaa** [comment]
> 



> 

你好，已发送好友请求

**Comment by xlliu7** [comment]
Thanks for your interest in this work. Currently, this repo only contains the model code. The full code is not ready for release.

**Comment by xlliu7** [comment]
Hi, the training code has been released.
